# Executable binary builder.
FROM golang:1.23.4-alpine AS Builder

# Setting the working directory.
WORKDIR $GOPATH/src/webapp/
# Copying the project files.
COPY . .

# Fetch dependancies using go get.
RUN go mod download
RUN go mod verify

# Build the binary for the webapp.
RUN go build -ldflags="-w -s" -o /go/bin/webapp

# Minimalistic small image as the final image with the sole purpose to run the binary.
FROM alpine:3.21.0

RUN apk --no-cache add ca-certificates

# Setting the working directory.
WORKDIR /webapp

COPY templates/ templates/
COPY assets/ assets/

# Get the built binary from the builder image.
COPY --from=Builder /go/bin/webapp /go/bin/webapp

# Run the built binary.
ENTRYPOINT ["/go/bin/webapp"]
